Homework6/Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_items = new HashSet<order_items>();
            this.stocks = new HashSet<stock>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int brand_id { get; set; }
        public int category_id { get; set; }
        public short model_year { get; set; }
        public decimal list_price { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock> stocks { get; set; }
    }
}

Homework6/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Homework6.Models;
using PagedList.Mvc;
using PagedList;
using Newtonsoft.Json;

namespace Homework6.Controllers
{
    public class productsController : Controller
    {
        private BikeStoresEntities db = new BikeStoresEntities();
        static string searchTrigger;
        // GET: products
        public ActionResult Index(int? i)
        {
            var products = db.products.Include(p => p.brand).Include(p => p.category);
            if (searchTrigger !=null)
            {
                products = db.products.Where(zz => zz.product_name.Contains(searchTrigger)).Include(p => p.brand).Include(p => p.category);
            }
            return View(products.ToList().ToPagedList(i ?? 1,10));
        }
        public ActionResult Search(string searchText)
        {
            //Don't forget to write a function to clear it and set the searchTrigger back to 0
            searchTrigger = searchText;
            var products = db.products.Where(zz => zz.product_name.Contains(searchTrigger)).Include(p => p.brand).Include(p => p.category);
            int? i = 1 ;
            return View("Index", products.ToList().ToPagedList(i ?? 1, 10));
        }
        public ActionResult EditView()
        {
            return PartialView();
        }
        public ActionResult CreateView()
        {
            return PartialView();
        }
        public string EditProd(int? id)
        {
            
            db.Configuration.ProxyCreationEnabled = false;
        
            object product = db.products.Where(x => x.product_id == id).Select(p => new { id = p.product_id, name = p.product_name, brand = p.brand.brand_name, catergory = p.category.category_name, model = p.model_year, price = p.list_price }).FirstOrDefault();
         
            return JsonConvert.SerializeObject(product);
        }
        public string CreateProd(int? id)
        {

            db.Configuration.ProxyCreationEnabled = false;

            object product = db.products.Select(p => new { id = p.product_id, name = p.product_name, brand = p.brand.brand_name, catergory = p.category.category_name, model = p.model_year, price = p.list_price }).FirstOrDefault();

            return JsonConvert.SerializeObject(product);
        }

        public string GetCatergoryNames()
        {
            object catergoryData = db.categories.Select(p => new { id = p.category_id, name = p.category_name }).ToList();
            return JsonConvert.SerializeObject(catergoryData);
        }
        public string GetBrandData()
        {
            db.Configuration.ProxyCreationEnabled = false;

            List<brand> data = db.brands.ToList();

            return JsonConvert.SerializeObject(data);
        }
        //For details
        public string ProductDetails(int id)
        {
            object productDetial = db.stocks.Where(y => y.product_id == id).Include(v => v.product).Select(p => new {
                productname = p.product.product_name,
                year = p.product.model_year,
                price = p.product.list_price,
                brand = p.product.brand.brand_name,
                catergory = p.product.category.category_name,
                stores = db.stocks.Where(s => s.product_id == id).Select(n => new { storename = n.store.store_name, quantity = n.quantity })

            }).FirstOrDefault();
            return JsonConvert.SerializeObject(productDetial);

        }
        public ActionResult Details(int? id)
        {
            return PartialView();
        }
        //For the deletes 
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            var products = db.products.Include(p => p.brand).Include(p => p.category);
            int? i = 1;
            return RedirectToAction("Index", products.ToList().ToPagedList(i ?? 1, 10));
        }
        public string GetProducts(int? i)
        {
            db.Configuration.ProxyCreationEnabled = false;
            object productDatas = db.products.Select(p => new { id = p.product_id, name = p.product_name, brand = p.brand.brand_name, catergory = p.category.category_name, model = p.model_year, price = p.list_price }).ToList().ToPagedList(i ?? 1, 10);
            return JsonConvert.SerializeObject(productDatas);
        }
        // GET: products/Create
        public ActionResult Create()
        {
            ViewBag.brand_id = new SelectList(db.brands, "brand_id", "brand_name");
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name");
            return View();
        }

        // POST: products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,product_name,brand_id,category_id,model_year,list_price")] product product)
        {
            if (ModelState.IsValid)
            {
                db.products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.brand_id = new SelectList(db.brands, "brand_id", "brand_name", product.brand_id);
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id);
            return View(product);
        }

        // GET: products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.brand_id = new SelectList(db.brands, "brand_id", "brand_name", product.brand_id);
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id);
            return PartialView("Edit_Partial_View", product);
        }

        // POST: products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,product_name,brand_id,category_id,model_year,list_price")] product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.brand_id = new SelectList(db.brands, "brand_id", "brand_name", product.brand_id);
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id);
            return RedirectToAction("Index");
        }

        public ActionResult Verify(int product_id, string product_name, int brand_id, int category_id, short model_year, decimal list_price)
        {
            product product = new product
            {
                product_id = product_id,
                product_name = product_name,
                brand_id = brand_id,
                category_id = category_id,
                model_year = model_year,
                list_price = list_price

            };
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                var products = db.products.Include(p => p.brand).Include(p => p.category);
                int? i = 1;
                return RedirectToAction("Index", products.ToList().ToPagedList(i ?? 1, 10));
            }
           
            return View(product);
        }

        public ActionResult AddFinal(int product_id, string product_name, int brand_id, int category_id, short model_year, decimal list_price)
        {
            product product = new product
            {
                product_id = product_id,
                product_name = product_name,
                brand_id = brand_id,
                category_id = category_id,
                model_year = model_year,
                list_price = list_price

            };
            if (ModelState.IsValid)
            {
                db.products.Add(product);
                db.SaveChanges();
                var products = db.products.Include(p => p.brand).Include(p => p.category);
                int? i = 1;
                return RedirectToAction("Index", products.ToList().ToPagedList(i ?? 1, 10));
            }
           
            return View(product);
        }

    }
}

Homework6/Views/products/Create.cshtml
@model Homework6.Models.product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brand_id, "brand_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("brand_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.brand_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model_year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.model_year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.model_year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.list_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.list_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.list_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Homework6/Views/products/Delete.cshtml
@model Homework6.Models.product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.model_year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.model_year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.brand.brand_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brand.brand_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category.category_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.category_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Homework6/Views/products/Details.cshtml
<div class="panel panel-default">
    <div class="panel-heading">Product Details</div>
    <div class="panel-body">
        <p>Name      <span id="name"></span></p>
        <p>Year      <span id="year"></span></p>
        <p>Price     <span id="price"></span></p>
        <p>Brand     <span id="brand"></span></p>
        <p>Catergory <span id="catergory"></span></p>

        <table class="table">

            <thead>
                <tr>
                    <th scope="col">Store</th>
                    <th scope="col">Quantity</th>
                </tr>
            </thead>
            <tbody id="stores"></tbody>
        </table>
    </div>

</div>

Homework6/Views/products/Edit.cshtml
@model Homework6.Models.product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.product_id)

        <div class="form-group">
            @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brand_id, "brand_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("brand_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.brand_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model_year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.model_year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.model_year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.list_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.list_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.list_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Homework6/Views/products/EditView.cshtml
<div class="form-group">
    <label for="exampleInputPassword1">Id</label>
    <input type="text" class="form-control" id="id">
</div>


<div class="form-group">
    <label for="exampleInputPassword1">Name</label>
    <input type="text" class="form-control" id="name">
</div>

<div class="form-group">
    <label for="exampleInputPassword1">Catergory</label>
    <select class="form-control" id="catergorySelect"></select><br />
</div>

<div class="form-group">
    <label>Price</label>
    <input type="number" class="form-control" id="price">
</div>

<div class="form-group">
    <label class="col-form-label">Brand:</label>
    <select id="brand-select" class="form-control"></select>
</div>

<div class="form-group">
    <label for="exampleInputPassword1">Model</label>
    <input type="text" class="form-control" id="model">
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Homework6/Views/products/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<Homework6.Models.product>
@using Homework6.Models
@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>*@


<h2>Products</h2>

<!-- Modal -->
<div class="modal fade modal-dialog-centered" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="partialView">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="Update()">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade modal-dialog-centered" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="partialView2">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="AddToDatabase()">Confirm Creation</button>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("Search", "products", FormMethod.Post, new { style = "width:100%" }))
{
    <table class="table">
        <tr>
            <th style="width:20%"><input type="text" style="max-width:none; display:flex" name="searchText" class="form-control" placeholder="Search" /></th>
            <th style="width:1%"><button type="submit" class="btn btn-success">Search</button></th>
            <th style="width:100%"><button type="button" class="btn btn-info" onclick="Create()">Create</button></th>
        </tr>
    </table>
}
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Year
        </th>
        <th>
            Price
        </th>
        <th>
            Brand
        </th>
        <th>
            Category
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.product_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.model_year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.list_price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.brand.brand_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.category.category_name)
            </td>
            <td>
                <button type="button" class="btn btn-primary btn-update" onclick="edit(@item.product_id)" data-id="@item.product_id">Edit</button>
                |
                <button type="button" class="btn btn-info btn-update" onclick="DetailsInfo(@item.product_id)" data-id="@item.product_id">Details</button> |
                <button type="button" class="btn btn-danger btn-update" onclick="Delete(@item.product_id)" data-id="@item.product_id">Delete</button>
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, i => Url.Action("Index", "products", new { i, search = Request.QueryString["search"] }))

<script>
    function edit(myid) {
        
            $('#exampleModal').modal('toggle');
            $('#partialView').load('/products/EditView');
            var Id = parseInt(myid)
        
             $.get({
                    url: "@Url.Action("EditProd", "products")",
                    data: {
                        id: myid,
                    },
                 success: (data, status) => {
                     console.log("Success!!");
                     let productsData = JSON.parse(data);
                     $('#id').val(productsData.id)
                     console.log("Test Val: " + $('#id').val())
                     $('#name').val(productsData.name);
                     $("#catergorySelect").empty();
                     $("#catergorySelect").append(`<option value="${productsData.id}">${productsData.catergory}</option>`);
                     FillCatergorySelect();
                     $('#price').val(productsData.price);
                     
                     $("#brand-select").empty();
                     $("#brand-select").append(`<option value="${productsData.id}">${productsData.brand}</option>`);
                     $('#model').val(productsData.model);
                     GetBrandData()
                    }
             });


    }
    function DetailsInfo(myid) {
            $('#exampleModal').modal('toggle');
        $('#partialView').load('/products/Details');

             $.get({
                    url: "@Url.Action("ProductDetails", "products")",
                    data: {
                        id: myid,

                    },
                 success: (data) => {

                     let product = JSON.parse(data);

                     $('#name').html(product.productname);
                     $('#year').html(product.year);
                     $('#price').html(product.price);
                     $('#catergory').html(product.catergory);
                     $('#brand').html(product.brand);

                     $(product.stores).each((i, e) => {
                         if (e.quantity == 0) {
                             $('#stores').append(`<tr><td>${e.storename}</td><td><p style="color:red">Out of stock</p></td></tr>`)
                         }
                         else {
                             $('#stores').append(`<tr><td>${e.storename}</td><td>${e.quantity}</td></tr>`)
                         }
                         
                     })

                    }
             });
    }
    function Delete(myid) {

             $.get({
                    url: "@Url.Action("DeleteConfirmed", "products")",
                    data: {
                        id: myid,

                    },
                 success: (data, status) => {
                    $('#exampleModal').modal('hide')
                    GetProducts();

                }
             });
    }

    function Update() {
        console.log("The ID is: " + parseInt($('#id').val()));
            $.get({
                url: "@Url.Action("Verify", "products")",
               
                data: {

                    product_id: parseInt($('#id').val()),
                    product_name: $('#name').val(),
                    category_id: parseInt($('#catergorySelect').val()),
                    list_price: parseFloat($('#price').val()),
                    brand_id: parseInt($('#brand-select').val()),
                    model_year: parseInt($('#model').val())
                    
                   
                },
                success: (data, status) => {
                    $('#exampleModal').modal('hide')
                    GetProducts();

                }
            })
    }
    function AddToDatabase() {
       
            $.get({
                url: "@Url.Action("AddFinal", "products")",
               
                data: {

                    product_id: parseInt($('#id').val()),
                    product_name: $('#name').val(),
                    category_id: parseInt($('#catergorySelect').val()),
                    list_price: parseFloat($('#price').val()),
                    brand_id: parseInt($('#brand-select').val()),
                    model_year: parseInt($('#model').val())
                    
                   
                },
                success: (data, status) => {
                    $('#exampleModal').modal('hide')
                    GetProducts();

                }
            })
    }
    function Create() {
        
        $('#exampleModal2').modal('toggle');
            $('#partialView2').load('/products/EditView');
            
        console.log("Create the called");
             $.get({
                    url: "@Url.Action("CreateProd", "products")",
                    data: {
                        id: 1,
                    },
                 success: (data, status) => {
                     console.log("Success!!");
                     let productsData = JSON.parse(data);
                     $('#id').val("")
                     
                     $('#name').val();
                     $("#catergorySelect").empty();
                     $("#catergorySelect").append(`<option value="${productsData.id}">${productsData.catergory}</option>`);
                     FillCatergorySelect();
                     $('#price').val();
                     
                     $("#brand-select").empty();
                     $("#brand-select").append(`<option value="${productsData.id}">${productsData.brand}</option>`);
                     $('#model').val();
                     GetBrandData()
                    }
             });


    }

    function GetProducts() {
                $.get({
                    url: "@Url.Action("GetProducts", "products")",
                    success: (data) => {
                        let productsData = JSON.parse(data);
                        $("#tableBody").empty();
                        $(productsData).each((i, element) => {
                            $("#tableBody").append(`<tr data-id="${element.id}">
                             <td>${element.name}</td>
                             <td>${element.model}</td>
                             <td>${element.price}</td>
                             <td>${element.brand}</td>
                             <td>${element.catergory}</td>
                             <td><button type="button" class="btn btn-primary btn-update" onclick="edit(${element.id})" data-id="${element.id}" >Edit</button></td>
                             <td><button class="btn btn-primary" id="btn-details"  onclick="ProductInfo(${element.id})">Details</button></td>"
                             <td><button class="btn btn-danger" id="btn-delete"  onclick="Delete(${element.id})">Delete</button></td>
                             </tr>`)
                        });
                    }
                });
    }


    function FillCatergorySelect() {

                 $.get({
                    url: "@Url.Action("GetCatergoryNames", "products")",
                    success: (data) => {
                        let productData = JSON.parse(data);
                        $(productData).each((i, e) => {
                            $("#catergorySelect").append(`<option value="${e.id}">${e.name}</option>`);
                        });
                    }
                });

    }

    function GetBrandData() {
                $.get({
                    url: "@Url.Action("GetBrandData", "products")",
                    method: "GET",
                    success: (data, status) => {
                        let inData = JSON.parse(data);
                        let select = $("#brand-select");

                        $(inData).each((i, v) => {
                            select.append(`<option value="${v.brand_id}">${v.brand_name}</option>`);
                        });
                    }
                });
    }

</script>